# Generated by Django 5.2 on 2025-04-22 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"managed": False},
        ),
    ]
